version = 0.1
[default.deploy.parameters]
stack_name = "stripe-events-listener-service"
resolve_s3 = true
s3_prefix = "stripe-events-listener-service"
region = "eu-west-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
